### ISSUE TITLE
Exception Crash issue

### ISSUE THREAD

**Issue by VandanaPansuria** [TapResearch/TapResearch-iOS-SDK#39] opened 2022-12-06 04:42 UTC
I recently met a weird crash which only appears in iOS 16.0, which I cannot reproduce.

Below is the stacktrace, Any infomation will be appreciated.

```
**Fatal Exception: NSInvalidArgumentException
*** -[NSThread start]: attempt to start the thread again**

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0xa248 __exceptionPreprocess
1  libobjc.A.dylib                0x17a68 objc_exception_throw
2  Foundation                     0x5aa1c __NSThread__start__
3  TapResearchSDK                 0x18910 (Missing UUID 417d62ee069e3ab48b210be8c09cf67a)
4  TapResearchSDK                 0x7db4 (Missing UUID 417d62ee069e3ab48b210be8c09cf67a)
5  CoreFoundation                 0x377c4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
6  CoreFoundation                 0xde75c ___CFXRegistrationPost_block_invoke
7  CoreFoundation                 0xc1a34 _CFXRegistrationPost
8  CoreFoundation                 0x4bdc8 _CFXNotificationPost
9  Foundation                     0x5c4dc -[NSNotificationCenter postNotificationName:object:userInfo:]
10 UIKitCore                      0x291e14 -[UIApplication _stopDeactivatingForReason:]
11 UIKitCore                      0x2918c4 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
12 UIKitCore                      0x2916b0 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
13 UIKitCore                      0x291260 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
14 UIKitCore                      0x29112c __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
15 UIKitCore                      0x96f5a0 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:]
16 UIKitCore                      0xa0796c _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
17 UIKitCore                      0x13d2d8 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
18 UIKitCore                      0x5af048 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.215
19 UIKitCore                      0x20fbec -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
20 UIKitCore                      0x20fa5c -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
21 UIKitCore                      0x20f89c -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
22 FrontBoardServices             0x3524 -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:]
23 FrontBoardServices             0x3360 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2
24 FrontBoardServices             0x6ae4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
25 FrontBoardServices             0x6a00 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke
26 libdispatch.dylib              0x3fdc _dispatch_client_callout
27 libdispatch.dylib              0x7a5c _dispatch_block_invoke_direct
28 FrontBoardServices             0x10f2c __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
29 FrontBoardServices             0x10ac8 -[FBSSerialQueue _targetQueue_performNextIfPossible]
30 FrontBoardServices             0x132a8 -[FBSSerialQueue _performNextFromRunLoopSource]
31 CoreFoundation                 0xd622c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
32 CoreFoundation                 0xe2614 __CFRunLoopDoSource0
33 CoreFoundation                 0x6651c __CFRunLoopDoSources0
34 CoreFoundation                 0x7beb8 __CFRunLoopRun
35 CoreFoundation                 0x811e4 CFRunLoopRunSpecific
36 GraphicsServices               0x1368 GSEventRunModal
37 UIKitCore                      0x3a2d88 -[UIApplication _run]
38 UIKitCore                      0x3a29ec UIApplicationMain
39 KloveriOSApp                   0x12ddc main + 35 (AppDelegate.swift:35)
40 ???                            0x1be82d948 (Missing)
```

**Comment by philip-tap** [comment] 2022-12-06 23:39
Hi @VandanaPansuria,

We are taking a look at this issue and will have a more in depth response tomorrow. At first glance we are not sure how this is happening, and the crash is not entirely indicative of us as the cause. 

If you are able to reproduce this or provide some steps and information we will work together to understand.

**Comment by psymike** [comment] 2022-12-14 16:43
Hi @VandanaPansuria - [v2.5.5](https://github.com/TapResearch/TapResearch-iOS-SDK/releases/tag/v2.5.5) should fix this crash. Please update and let us know if you continue to see the issue. Thanks!

**Comment by VandanaPansuria** [comment] 2022-12-14 17:05
> Hi @VandanaPansuria - [v2.5.5](https://github.com/TapResearch/TapResearch-iOS-SDK/releases/tag/v2.5.5) should fix this crash. Please update and let us know if you continue to see the issue. Thanks!

Ok, Thank you. I will update the SDK and I will let you know if I get to continue after the update.

**Comment by psymike** [comment] 2023-01-18 23:22
Hi @VandanaPansuria - we've tried to reproduce this error and are unable to, so I'm going to close this ticket. If you continue to see the error on our latest SDK version, then please reopen. Thanks!

**Closed by psymike** 2023-01-18 23:22 UTC
